#!/usr/bin/env bash

## Description: Run PHPCBF (Drupal standards, GitLab-pipeline-equivalent config) against the flysystem module
## Usage: phpcsfix
## Example: "ddev phpcsfix"

set -e

cd /var/www/html
vendor/bin/phpcbf \
  --standard=.ddev/commands/web/phpcs.xml.dist \
  web/modules/custom/flysystem \
  "$@"