#!/usr/bin/env bash

## Description: Run PHPCS (Drupal standards, GitLab-pipeline-equivalent config) against the flysystem module
## Usage: phpcs
## Example: "ddev phpcs"

set -e

cd /var/www/html
vendor/bin/phpcs \
  --standard=.ddev/commands/web/phpcs.xml.dist \
  web/modules/custom/flysystem \
  "$@"